create table if not exists houses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  location text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists dues (
  id bigint generated by default as identity primary key,
  house_id bigint references houses on delete cascade not null,
  year int not null,
  amount numeric(12,2) not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists payments (
  id bigint generated by default as identity primary key,
  house_id bigint references houses on delete cascade not null,
  year int not null,
  amount numeric(12,2) not null,
  date date,
  method text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table houses enable row level security;
alter table dues enable row level security;
alter table payments enable row level security;

create policy "houses_select_own" on houses for select using (auth.uid() = user_id);
create policy "houses_insert_own" on houses for insert with check (auth.uid() = user_id);
create policy "houses_update_own" on houses for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "houses_delete_own" on houses for delete using (auth.uid() = user_id);

create policy "dues_select_own" on dues for select using (
  exists (select 1 from houses where houses.id = dues.house_id and houses.user_id = auth.uid())
);
create policy "dues_insert_own" on dues for insert with check (
  exists (select 1 from houses where houses.id = dues.house_id and houses.user_id = auth.uid())
);
create policy "dues_delete_own" on dues for delete using (
  exists (select 1 from houses where houses.id = dues.house_id and houses.user_id = auth.uid())
);

create policy "payments_select_own" on payments for select using (
  exists (select 1 from houses where houses.id = payments.house_id and houses.user_id = auth.uid())
);
create policy "payments_insert_own" on payments for insert with check (
  exists (select 1 from houses where houses.id = payments.house_id and houses.user_id = auth.uid())
);
create policy "payments_delete_own" on payments for delete using (
  exists (select 1 from houses where houses.id = payments.house_id and houses.user_id = auth.uid())
);

create index if not exists idx_houses_user_id on houses(user_id);
create index if not exists idx_dues_house_id on dues(house_id);
create index if not exists idx_payments_house_id on payments(house_id);
